### ISSUE TITLE
Support Erlang Distribution

### ISSUE THREAD

**Issue by jjcarstens** [nerves-project/nerves_pack#22]
Erlang distribution can mostly be configured by editing `vm.args.eex` of your firmware, but it might be nice to handle it in a more controlled fashion within NervesPack. (much like nerves_init_gadget did)

**Comment by fhunleth** [comment]
I think it has to be done at runtime, since unless you're hardcoding the node name to `something@nerves.local`, the hostname isn't known until runtime.

**Comment by fhunleth** [comment]
Closing since I think this issue is dated now and we've decided that enabling Erlang distribution is few enough lines of code that adding it to your project is the best way to go.
