### ISSUE TITLE
Can't get the ip by usb

### ISSUE THREAD

**Issue by LynnL4** [nerves-project/nerves_pack#46]
First of all, thanks a lot for this awesome project. I am using the bbb project on bbg and I can't get the ipby usb (no virtual network card enumerated), but I can get the correct ip address by eth. I can be sure that my cable is ok because in the official bbb image it is working. Do you have any suggestions for this, thanks!

**Comment by ConnorRigby** [comment]
do you have code anywhere? how did you generate your project? 
Could you try [this](https://github.com/elixir-circuits/circuits_quickstart/) as a test?

**Comment by LynnL4** [comment]
Hi ConnorRigby 
Yes, I've tested this project, both my own compiled image and the released image have the same result. And I've also tried it in pocketbeaglebone, both with the same result. When I first plugged in, my PC would prompt that it was configuring the network card, but in the device list, no new network card was added, and no network card was found in the available network adapters, then a serial port would be enumerated, but I couldn't open this one.
Thanks!

**Comment by ConnorRigby** [comment]
What is your host operating system?

**Comment by LynnL4** [comment]
HI，

**Comment by LynnL4** [comment]
HI，
I found this **https://github.com/nerves-project/nerves_system_bbb/blob/main/CHANGELOG.md#v252**.

**Comment by LynnL4** [comment]
Hi, 
I found a solution, the reason is the window driver problem, by loading a driver can solve the problem
- https://answers.microsoft.com/en-us/windows/forum/windows_10-networking-winpc/windows-10-vs-remote-ndis-ethernet-usbgadget-not/cb30520a-753c-4219-b908-ad3d45590447

- https://www.mobileread.com/forums/showthread.php?p=3283986
